### ISSUE TITLE
windows 10 64bit，anacoda_go don't work 

### ISSUE THREAD

**Issue by taixs** [DamnWidget/anaconda_go#1]
ST3 build version： 3126
Anaconda version： 2.15
AnacondaGO version： 1.3
Go version： 1.7.3， 64bit
Python interpreter version： try 2.7.12， 32bit  and 3.5.2 64bit/32bit
Operating System version： windows 10， 64bit
GOPATH： E:/GO, wirte in user setting
GOROOT： E:/GP, wirte in iser setting

I first install Anaconda, and install Anaconda_go.
Anaconda  work very well ，but  anaconda_go don't work.
i have try to remove another package, only install anaconda  and anaconda_go.

**Comment by DamnWidget** [comment]
Hi, please answer the following questions:
- Is there any error messages in the ST3 console log? 
- Anything in `%APPDATA%\Anaconda\Logs`?

**Comment by taixs** [comment]
Nothing in %APPDATA%\Anaconda\Logs
and
ST3 console log：

DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /Z/st3/sublime_text.exe
working dir: /Z/st3
packages path: /Z/st3/Data/Packages
state path: /Z/st3/Data/Local
zip path: /Z/st3/Packages
zip path: /Z/st3/Data/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.112631
startup time: 0.155631
first paint time: 0.156631
first paint time: 0.157631
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin anaconda_go.anaconda_go
No module named 'anaconda'
Traceback (most recent call last):
  File "lib.plugin in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 8, in <module>
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib.plugin in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 34, in <module>
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Z:\st3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "Z:\st3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "anaconda_go in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "Z:\st3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lib in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "Z:\st3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lib.helpers in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "Z:\st3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lib.plugin in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 42, in <module>
RuntimeError: Anaconda plugin is not installed!
reloading plugin anaconda_go.plugin_version
Traceback (most recent call last):
  File "Z:\st3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "Z:\st3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugin_version in Z:\st3\Data\Installed Packages\anaconda_go.sublime-package", line 9, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\st3\Data\Installed Packages\anaconda_go.sublime-package\messages.json'
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2016-11-09 00:29:47, next run at 2016-11-09 01:29:47 or after

**Comment by DamnWidget** [comment]
Looks like I forgot to add the `.no-sublime-package` file to the repo (as I use the git cloned repo instead of the Package Control to install it).

Version v0.1.4 (https://github.com/DamnWidget/anaconda_go/releases/tag/v0.1.4) adds the .no-sublime-package file so as soon as the version is available on Package Control you just uninstall anaconda_go and install it again.

Let me know if you have any other problem after do so.

**Comment by taixs** [comment]
I test 1.4 , can work.
but only show "Show erroe list" , "Next lint error" , "Previous lint error" 
another can't be use.

ST3 console log：
...
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin anaconda_go.anaconda_go
No module named 'anaconda'
Traceback (most recent call last):
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 8, in <module>
    from anaconda.anaconda_lib.worker import Worker
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 34, in <module>
    from anaconda.anaconda_lib.explore_panel import ExplorerPanel
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Server\editor\st3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\anaconda_go.py", line 10, in <module>
    from anaconda_go.lib import go
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib__init__.py", line 11, in <module>
    from anaconda_go.lib.helpers import project_name
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\helpers.py", line 13, in <module>
    from .plugin import anaconda_helpers
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 42, in <module>
    raise RuntimeError('Anaconda plugin is not installed!')
RuntimeError: Anaconda plugin is not installed!
reloading plugin anaconda_go.plugin_version
plugins loaded

**Comment by DamnWidget** [comment]
Looks like you don't have anaconda installed or it is disabled.

**Comment by taixs** [comment]
I have installed anaconda and anaconda_go.
anaconda work very well ,but anaconda_go can't work well.

## anacond console log：

reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin anaconda_go.anaconda_go
No module named 'anaconda'
Traceback (most recent call last):
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 8, in <module>
    from anaconda.anaconda_lib.worker import Worker
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 34, in <module>
    from anaconda.anaconda_lib.explore_panel import ExplorerPanel
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Server\editor\st3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\anaconda_go.py", line 10, in <module>
    from anaconda_go.lib import go
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib__init__.py", line 11, in <module>
    from anaconda_go.lib.helpers import project_name
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\helpers.py", line 13, in <module>
    from .plugin import anaconda_helpers
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 42, in <module>
    raise RuntimeError('Anaconda plugin is not installed!')
RuntimeError: Anaconda plugin is not installed!
reloading plugin anaconda_go.plugin_version
plugins loaded

## anaconda_go console log：

reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin anaconda_go.anaconda_go
No module named 'anaconda'
Traceback (most recent call last):
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 8, in <module>
    from anaconda.anaconda_lib.worker import Worker
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 34, in <module>
    from anaconda.anaconda_lib.explore_panel import ExplorerPanel
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Server\editor\st3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\anaconda_go.py", line 10, in <module>
    from anaconda_go.lib import go
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib__init__.py", line 11, in <module>
    from anaconda_go.lib.helpers import project_name
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\helpers.py", line 13, in <module>
    from .plugin import anaconda_helpers
  File "D:\Server\editor\st3\Data\Packages\anaconda_go\lib\plugin.py", line 42, in <module>
    raise RuntimeError('Anaconda plugin is not installed!')
RuntimeError: Anaconda plugin is not installed!
reloading plugin anaconda_go.plugin_version
plugins loaded

**Comment by DamnWidget** [comment]
Using Package Control, uninstall anaconda_go, then install it again it should work

**Comment by taixs** [comment]
All of anaconda_go is OK !
Thank you very much !
