### ISSUE TITLE
Autocomplete bug ?

### ISSUE THREAD

**Issue by eliangidoni** [DamnWidget/anaconda_go#16]
I'm having an issue on OSX after upgrading Sublime.
*Sublime version 3 build 3143.*
*go version go1.9 darwin/amd64*

The autocomplete shows up with options and just after, it hides and only shows a single option saying *PANIC PANIC PANIC*.

I checked Anaconda for Python and autocomplete works perfect.

See screenshot below, it should suggest `channel` as option, but:

<img width="546" alt="screen shot 2017-09-21 at 4 23 37 pm" src="https://user-images.githubusercontent.com/1263632/30704027-497b3f4e-9ee9-11e7-8939-90993f26b2ca.png">

**Comment by DamnWidget** [comment]
Did you update your Go version recently?  In any case, run `gocode close` and try again

**Comment by eliangidoni** [comment]
Yes I did update my go version. Whats the difference ?

**Comment by DamnWidget** [comment]
You probably need to recompile gocode using your new go version you can do it just  running:
`go get -u github.com/nsf/gocode`

**Comment by eliangidoni** [comment]
@DamnWidget Thank you! updating gocode helped me. Can you please add a note in known issues about this ? because it was very frustrating to understand the problem.

**Comment by DamnWidget** [comment]
Do you think you could add it yourself and make a PR? I am extremely busy lately :(

**Comment by eliangidoni** [comment]
Of course.... oh by the way, it seems my files are not being passed through goimports again. is that possible ? or is there a way to enable it ?

**Comment by eliangidoni** [comment]
will do it.

**Comment by eliangidoni** [comment]
@DamnWidget I got this after opening sublime
```
Traceback (most recent call last):
  File "/Users/elian/Library/Application Support/Sublime Text 3/Packages/anaconda_go/commands/fill_browse.py", line 50, in _run
    cache.load_package_cache()
  File "/Users/elian/Library/Application Support/Sublime Text 3/Packages/anaconda_go/lib/cache.py", line 97, in load_package_cache
    PACKAGES_CACHE[go.GOROOT] = json.load(fd)
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting object: line 1 column 204676153 (char 204676152)
None
```

The status keeps showing me the message `Building packages navigation cache` I think as a result of the crash. You have any solution ?

**Comment by DamnWidget** [comment]
Looks like your cache is corrupted. The only way to fix it is to get rid of it.

Stop ST3 and delete `~/Library/Application Support/Anaconda/cache/<your_project>/packages.cache`. After that the cache would be regenerated next time that you start ST3.

**Comment by eliangidoni** [comment]
yeah strange because i closed sublime after the cache finished being generated. will delete it then.

**Comment by eliangidoni** [comment]
Ok. Just created the PR to update the README. Thank you !
