### ISSUE TITLE
RuntimeError: goimports not found...

### ISSUE THREAD

**Issue by kden416** [DamnWidget/anaconda_go#18]
after install, i have this in console:
```
ERROR:root:Your operating system denied the spawn of /home/user/coding/go/bin/guru process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
The OS did return [Errno 2] No such file or directory: '/home/user/coding/go/bin/guru'
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Packages/anaconda_go/commands/fill_browse.py", line 67, in _run
    self.process(out.decode('utf8'))
  File "/home/user/.config/sublime-text-3/Packages/anaconda_go/commands/fill_browse.py", line 124, in process
    out, err = guru.communicate()
AttributeError: 'NoneType' object has no attribute 'communicate'
None
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/user/.config/sublime-text-3/Packages/anaconda_go/commands/format.py", line 63, in run
    self.goimports(code, path, edit)
  File "/home/user/.config/sublime-text-3/Packages/anaconda_go/commands/format.py", line 76, in goimports
    raise RuntimeError('goimports not found...')
RuntimeError: goimports not found...
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/user/.config/sublime-text-3/Packages/anaconda_go/commands/format.py", line 63, in run
    self.goimports(code, path, edit)
  File "/home/user/.config/sublime-text-3/Packages/anaconda_go/commands/format.py", line 76, in goimports
    raise RuntimeError('goimports not found...')
RuntimeError: goimports not found...

```

**Comment by DamnWidget** [comment]
The error says that you don't have goimports installed, try installing it

**Comment by kden416** [comment]
after reinstalling plugin, all works fine.
