### ISSUE TITLE
Issues on OS X 10.11.6

### ISSUE THREAD

**Issue by sdemura** [DamnWidget/anaconda_go#2]
```startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/sean/Library/Application Support/Sublime Text 3/Packages
state path: /Users/sean/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/sean/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.408988
using gpu buffer for window
first paint time: 0.460089
using gpu buffer for window
startup time: 0.636157
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Git.git_commands
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_gutter_jump_to_changes
reloading plugin GitGutter.git_gutter_popup
reloading plugin GitGutter.git_gutter_settings
reloading plugin GitGutter.git_gutter_show_diff
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.promise
reloading plugin GoGuru.goGuru
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Origami.origami
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageSync.PackageSync
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
reloading plugin SublimeLinter-pep8.linter
SublimeLinter: pep8 linter loaded 
reloading plugin SublimeLinter-pyflakes.linter
SublimeLinter: pyflakes linter loaded 
reloading plugin SublimeLinter-shellcheck.linter
SublimeLinter: shellcheck linter loaded 
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin Terminal.Terminal
reloading plugin zz File Icons.File Icons
plugins loaded
SublimeLinter: cannot find the gutter theme '', using the default 
SublimeLinter: debug mode: off 
GoGuru: ('debug:', False)
GoGuru: ('use_golangconfig', False)
GoGuru: ('version:', '0.1.14')
reloading settings Packages/User/PackageSync.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2017-01-30 13:54:33, next run at 2017-01-30 14:54:33 or after
ignored packages updated to: ["anaconda_go", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin anaconda_go.anaconda_go
No module named 'Anaconda.anaconda_lib.enum'
Traceback (most recent call last):
  File "/Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/lib/plugin.py", line 8, in <module>
    from anaconda.anaconda_lib.worker import Worker
ImportError: No module named 'anaconda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/lib/plugin.py", line 32, in <module>
    from Anaconda.anaconda_lib.enum import Enum, IntEnum, unique
ImportError: No module named 'Anaconda.anaconda_lib.enum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/anaconda_go.py", line 10, in <module>
    from anaconda_go.lib import go
  File "/Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/lib/__init__.py", line 11, in <module>
    from anaconda_go.lib.helpers import project_name
  File "/Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/lib/helpers.py", line 13, in <module>
    from .plugin import anaconda_helpers
  File "/Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/lib/plugin.py", line 41, in <module>
    raise RuntimeError('Anaconda plugin is not installed!')
RuntimeError: Anaconda plugin is not installed!
reloading plugin anaconda_go.plugin_version
generating syntax summary
reloading /Users/sean/Library/Application Support/Sublime Text 3/Packages/anaconda_go/Anaconda_GO.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

Anaconda is installed and works perfectly. AnacondaGO however, does not.

**Comment by DamnWidget** [comment]
Thank you for the warning, I repacked version v0.1.5 try to uninstall and install it again.

**Comment by sdemura** [comment]
```anaconda_go: finished detecting environment in 0.5236411094665527s```

We are in business! Thanks!
